const GAME_WIDTH = 400;
const GAME_HEIGHT = 600;

const PLAYER_WIDTH = 30;
const PLAYER_HEIGHT = 20;
const PLAYER_SPEED = 5;

const BULLET_WIDTH = 5;
const BULLET_HEIGHT = 15;
const BULLET_LIMIT = 2;
const PLAYER_BULLET_SPEED = 15;
const ENEMY_BULLET_SPEED = 5;

const ENEMY_WIDTH = 25;
const ENEMY_HEIGHT = 15;
const ENEMY_OFFSET = 15;
const ENEMY_SCORE = 10;
const ENEMY_CONTAINER_X_PADDING = 30;
const ENEMY_CONTAINER_Y_PADDING = 50;
const ENEMY_SPEED_INCREMENT = 0.05;
const ENEMY_SPEED_THRESHOLD = 0.7;
const ENEMY_Y_LIMIT = 500;

let ENEMY_SPEED = 0.2;
let ENEMY_DIR = 1;

const NUMBER_OF_ENEMIES_PER_LINE = 8;
const NUMBER_OF_ENEMY_LINES = 5;

let GAME_STATE = 'play';