const GAME_WIDTH = 400;
const GAME_HEIGHT = 600;

const PLAYER_WIDTH = 30;
const PLAYER_HEIGHT = 20;
const PLAYER_SPEED = 5;

const ENEMY_WIDTH = 45;
const ENEMY_HEIGHT = 35;
const ENEMY_OFFSET = 15;
const ENEMY_CONTAINER_X_PADDING = 50;
const ENEMY_CONTAINER_Y_PADDING = 70;